flip to perl for more control of script

diff --git a/update-resolv-conf b/update-resolv-conf
--- a/update-resolv-conf
+++ b/update-resolv-conf
@@ -1,65 +1,65 @@
-#!/bin/bash
-# 
-# Adjusted for CentOS7/RHEL/Fedora
+#!/usr/bin/perl
 #
-# Note: ideally networKManager would handle this via dnsmasq, but it doesn't
+# Note: ideally NetworkManager would handle this via dnsmasq, but it doesn't
 # appear to handle this dynamically as of yet.  So we'll just clobber it.
 # We run the risk that NeworkManager will replace it later..
 #
 # Parses DHCP options from openvpn to update resolv.conf
 # To use set as 'up' and 'down' script in your openvpn *.conf:
+#
 # up /etc/openvpn/update-resolv-conf
 # down /etc/openvpn/update-resolv-conf
-#
-# Used snippets of resolvconf script by Thomas Hood and Chris Hanson.
-# Licensed under the GNU GPL.  See /usr/share/common-licenses/GPL. 
-# 
-# Example envs set from openvpn:
-#
-#     foreign_option_1='dhcp-option DNS 193.43.27.132'
-#     foreign_option_2='dhcp-option DNS 193.43.27.133'
-#     foreign_option_3='dhcp-option DOMAIN be.bnc.ch'
-#
 
-# resolv.conf needs to be readable by all
-umask 022
-datestamp="%a %b %d %H:%M:%S %Y"
+use POSIX q{strftime};
+use strict;
 
-case "$script_type" in
-  up)
-    NMSRVRS=""
-    SRCHS=""
-    for optionvarname in ${!foreign_option_*} ; do
-        read -r -a opts <<< "${!optionvarname}"
-        echo "$(date "+$datestamp") - vpn push option: ${opts[0]} ${opts[1]} ${opts[2]}"
-        if [ "${opts[0]}" = "dhcp-option" ] ; then
-            if [ "${opts[1]}" = "DNS" ] ; then
-                NMSRVRS="${NMSRVRS:+$NMSRVRS }${opts[2]}"
-            elif [ "${opts[1]}" = "DOMAIN" ] ; then
-                SRCHS="${SRCHS:+$SRCHS }${opts[2]}"
-            fi
-        fi
-    done
-    RESCONF=""
-    [ "$SRCHS" ] && RESCONF="search $SRCHS
-"
-    for NS in $NMSRVRS ; do
-            RESCONF="${R}nameserver $NS
-"
-    done
-    cp /etc/resolv.conf "/etc/resolv.conf.pre:$dev"
-    cat > /etc/resolv.conf <<END
+my $script_type = $ENV{'script_type'};
+my $dev = $ENV{'dev'};
+my $resconf = "/etc/resolv.conf";
+
+sub log {
+    print strftime("%a %b %d %H:%M:%S %Y ", localtime()), @_, "\n";
+}
+
+if ($script_type eq "up") {
+    my @servers = ();
+    my @search = ();
+	for my $key (sort keys %ENV) {
+        if ($key !~ /^foreign_option_/) {
+            next;
+        }
+        my ($type, $name, $value) = split(/\s+/, $ENV{$key});
+        if ($type ne "dhcp-option") {
+            next;
+        }
+        if ($name eq "DNS") {
+            push(@servers, $value);
+        } elsif ($name eq "DOMAIN") {
+            @search = ($value, grep(/^$value$/, @search));
+        } elsif ($name eq "DOMAIN-SEARCH") {
+            if (!grep(/^$value$/, @search)) {
+                push(@search, $value);
+            }
+        }
+    }
+
+    system("cp", $resconf, "$resconf.pre:$dev");
+    open(OUT, ">", $resconf) || die("Unable to open ($resconf): $!");
+    my $srch = join(" ", @search);
+    &log("dns search $srch");
+    print OUT <<END;
 # generated by /etc/openvpn/update-resolv-conf
-$RESCONF
+search $srch
 END
-    ;;
-  down)
-    if [ -f "/etc/resolv.conf.pre:$dev" ]; then
-        mv "/etc/resolv.conf.pre:$dev" /etc/resolv.conf
-    fi
-    ;;
-  *)
-    echo "Unknown argument: $script_type";
-    ;;
-esac
+    for my $svr (@servers) {
+        &log("dns nameserver $svr");
+        print OUT "nameserver $svr\n";
+	}
+    close(OUT);
+    chmod($resconf, 0644);
+} elsif ($script_type eq "down") {
+    if (-f "$resconf.pre:$dev") {
+        rename("$resconf.pre:$dev", $resconf);
+    }
+}
 
